name = "investing-scrape-data"
main = "dist/worker.js"
compatibility_date = "2024-02-03"
compatibility_flags = ["nodejs_compat"]

[vars]
NODE_ENV = "production"

# Add your environment variables here
# DATABASE_URL = ""
# SUPABASE_URL = ""
# SUPABASE_KEY = ""

[build]
command = "bun run build"
watch_dir = "src"

[build.upload]
format = "modules"
main = "dist/worker.js"
dir = "dist"

[miniflare]
kv_persist = true
cache_persist = true

# Add dev environment variables
[env.dev]
vars = { NODE_ENV = "development" }

# Add staging environment variables
[env.staging]
vars = { NODE_ENV = "staging" }

# Add production environment variables
[env.production]
vars = { NODE_ENV = "production" }
